# Generated by Django 4.0.6 on 2022-07-15 07:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_sweet'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sweet',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
