# Generated by Django 4.0.6 on 2022-07-18 05:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_sweet_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sweet',
            managers=[
                ('sweets', django.db.models.manager.Manager()),
            ],
        ),
    ]
